"""
Simplified Book Recommender Dashboard

This dashboard showcases the zero-shot classification results using facebook/bart-large-mnli.
It provides a simple interface to browse and filter books by category.
"""

import pandas as pd
import gradio as gr

# Load the books with categories (generated by facebook/bart-large-mnli)
books = pd.read_csv("outputs/books_with_categories.csv")

# Create large thumbnails
books["large_thumbnail"] = books["thumbnail"] + "&fife=w800"
books["large_thumbnail"] = books["large_thumbnail"].fillna("https://via.placeholder.com/400x600?text=No+Cover")

def search_books(query: str, category: str = "All", max_results: int = 16):
    """
    Search and filter books based on query and category.
    
    Args:
        query: Search term to match in title, authors, or description
        category: Fiction, Nonfiction, or All
        max_results: Maximum number of results to return
    
    Returns:
        List of tuples (image_url, caption) for Gradio Gallery
    """
    # Filter by category
    if category != "All":
        filtered_books = books[books["simple_categories"] == category]
    else:
        filtered_books = books
    
    # Search in title, authors, and description
    if query.strip():
        mask = (
            filtered_books["title"].str.contains(query, case=False, na=False) |
            filtered_books["authors"].str.contains(query, case=False, na=False) |
            filtered_books["description"].str.contains(query, case=False, na=False)
        )
        filtered_books = filtered_books[mask]
    
    # Limit results
    filtered_books = filtered_books.head(max_results)
    
    # Format results for gallery
    results = []
    for _, row in filtered_books.iterrows():
        # Truncate description
        description = str(row["description"])
        truncated_desc = " ".join(description.split()[:30]) + "..."
        
        # Format authors
        authors_split = str(row["authors"]).split(";")
        if len(authors_split) == 2:
            authors_str = f"{authors_split[0]} and {authors_split[1]}"
        elif len(authors_split) > 2:
            authors_str = f"{', '.join(authors_split[:-1])}, and {authors_split[-1]}"
        else:
            authors_str = row["authors"]
        
        # Create caption with category info
        caption = f"**{row['title']}** by {authors_str}\n\n*Category: {row['simple_categories']}*\n\n{truncated_desc}"
        results.append((row["large_thumbnail"], caption))
    
    return results

def get_stats():
    """Get statistics about the classified books."""
    total = len(books)
    fiction = len(books[books["simple_categories"] == "Fiction"])
    nonfiction = len(books[books["simple_categories"] == "Nonfiction"])
    
    stats_text = f"""
    ### Classification Statistics (using facebook/bart-large-mnli)
    
    - **Total Books**: {total:,}
    - **Fiction**: {fiction:,} ({fiction/total*100:.1f}%)
    - **Nonfiction**: {nonfiction:,} ({nonfiction/total*100:.1f}%)
    """
    return stats_text

# Get unique categories
categories = ["All"] + sorted(books["simple_categories"].dropna().unique().tolist())

# Create Gradio interface
with gr.Blocks() as dashboard:
    gr.Markdown("# 📚 Book Recommender - Zero-Shot Classification Demo")
    gr.Markdown("*Powered by facebook/bart-large-mnli for Fiction/Nonfiction classification*")
    
    # Statistics
    with gr.Accordion("📊 Classification Statistics", open=False):
        stats = gr.Markdown(get_stats())
    
    # Search interface
    with gr.Row():
        query_input = gr.Textbox(
            label="Search books",
            placeholder="e.g., science fiction, mystery, love story...",
            scale=3
        )
        category_dropdown = gr.Dropdown(
            choices=categories,
            label="Filter by Category",
            value="All",
            scale=1
        )
        search_button = gr.Button("🔍 Search", variant="primary", scale=1)
    
    # Results gallery
    gr.Markdown("## 📖 Results")
    output_gallery = gr.Gallery(
        label="Book Recommendations",
        columns=4,
        rows=4,
        height="auto",
        object_fit="contain"
    )
    
    # Event handlers
    search_button.click(
        fn=search_books,
        inputs=[query_input, category_dropdown],
        outputs=output_gallery
    )
    
    # Load initial results
    dashboard.load(
        fn=lambda: search_books("", "All", 16),
        outputs=output_gallery
    )
    
    # Footer
    gr.Markdown("""
    ---
    **Note**: This is a simplified demo showcasing the zero-shot classification results.
    The full version includes semantic search with OpenAI embeddings and sentiment analysis.
    """)

if __name__ == "__main__":
    dashboard.launch(share=True, server_name="127.0.0.1", server_port=7860)
